/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dragonfish

import (
	"encoding/json"
	"fmt"
)

// FilesystemSetacl0DaclInner - struct for FilesystemSetacl0DaclInner
type FilesystemSetacl0DaclInner struct {
	MapmapOfStringinterface{} *map[string]interface{}
}

// map[string]interface{}AsFilesystemSetacl0DaclInner is a convenience function that returns map[string]interface{} wrapped in FilesystemSetacl0DaclInner
func MapmapOfStringinterface{}AsFilesystemSetacl0DaclInner(v *map[string]interface{}) FilesystemSetacl0DaclInner {
	return FilesystemSetacl0DaclInner{
		MapmapOfStringinterface{}: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *FilesystemSetacl0DaclInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MapmapOfStringinterface{}
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringinterface{})
	if err == nil {
		jsonMapmapOfStringinterface{}, _ := json.Marshal(dst.MapmapOfStringinterface{})
		if string(jsonMapmapOfStringinterface{}) == "{}" { // empty struct
			dst.MapmapOfStringinterface{} = nil
		} else {
			match++
		}
	} else {
		dst.MapmapOfStringinterface{} = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MapmapOfStringinterface{} = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(FilesystemSetacl0DaclInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(FilesystemSetacl0DaclInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FilesystemSetacl0DaclInner) MarshalJSON() ([]byte, error) {
	if src.MapmapOfStringinterface{} != nil {
		return json.Marshal(&src.MapmapOfStringinterface{})
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FilesystemSetacl0DaclInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.MapmapOfStringinterface{} != nil {
		return obj.MapmapOfStringinterface{}
	}

	// all schemas are nil
	return nil
}

type NullableFilesystemSetacl0DaclInner struct {
	value *FilesystemSetacl0DaclInner
	isSet bool
}

func (v NullableFilesystemSetacl0DaclInner) Get() *FilesystemSetacl0DaclInner {
	return v.value
}

func (v *NullableFilesystemSetacl0DaclInner) Set(val *FilesystemSetacl0DaclInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesystemSetacl0DaclInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesystemSetacl0DaclInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesystemSetacl0DaclInner(val *FilesystemSetacl0DaclInner) *NullableFilesystemSetacl0DaclInner {
	return &NullableFilesystemSetacl0DaclInner{value: val, isSet: true}
}

func (v NullableFilesystemSetacl0DaclInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesystemSetacl0DaclInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


